# Generated by scripts/homebrew-cask.ts in Bakar0/daedalus. Do not edit by hand.
cask "daedalus" do
  arch arm: "arm64", intel: "x64"

  version "0.14.0"
  sha256 arm:   "f8664245eb416fb2cfbe458acbea54e3d1afe0485a70a2e1038f32966ec200e0",
         intel: "18f2e5f8e5bec310e13eb61160f65334a4ee655de31c627b0adf8c93e8097cd4"

  url "https://github.com/Bakar0/daedalus/releases/download/v#{version}/stable-macos-#{arch}-Daedalus.dmg"
  name "Daedalus"
  desc "Desktop app and CLI for running coding agents in tmux"
  homepage "https://github.com/Bakar0/daedalus"

  livecheck do
    url :url
    strategy :github_latest
  end

  # The app updates itself from GitHub Releases, so `brew upgrade` leaves it
  # alone unless asked with --greedy.
  auto_updates true
  depends_on macos: :sonoma

  app "Daedalus.app"
  # Puts `daedal` on PATH. The launcher runs the CLI inside the app.
  binary "#{appdir}/Daedalus.app/Contents/Resources/bin/daedal"

  # This build is not notarized. Homebrew quarantines what it installs, and
  # Gatekeeper refuses to open an unnotarized app from quarantine.
  postflight_steps do
    run "/usr/bin/xattr",
        args:           ["-dr", "com.apple.quarantine", "{{appdir}}/Daedalus.app"],
        writable_paths: ["{{appdir}}/Daedalus.app"]
  end

  # ~/.daedalus holds the user's workspaces and database, so it is never
  # removed here, not even by --zap.
  zap trash: [
    "~/Library/Application Support/dev.daedalus.app",
    "~/Library/Caches/dev.daedalus.app",
    "~/Library/Preferences/dev.daedalus.app.plist",
  ]
end
