# Generated by scripts/homebrew-cask.ts in Bakar0/daedalus. Do not edit by hand.
cask "daedalus" do
  arch arm: "arm64", intel: "x64"

  version "0.8.0"
  sha256 arm:   "0efbb4917cdad653fd2052e55ab4bc9fc70dc1ae0a47fccb97d4faf57a0d3b53",
         intel: "6b5c1d2ec9606207ac728887cce3595885c9b482b198de584d14266f856af98d"

  url "https://github.com/Bakar0/daedalus/releases/download/v#{version}/stable-macos-#{arch}-Daedalus.dmg"
  name "Daedalus"
  desc "Desktop app and CLI for running coding agents in tmux"
  homepage "https://github.com/Bakar0/daedalus"

  livecheck do
    url :url
    strategy :github_latest
  end

  # The app updates itself from GitHub Releases, so `brew upgrade` leaves it
  # alone unless asked with --greedy.
  auto_updates true
  depends_on macos: ">= :sonoma"

  app "Daedalus.app"

  # This build is not notarized. Homebrew quarantines what it installs, and
  # Gatekeeper refuses to open an unnotarized app from quarantine.
  postflight_steps do
    run "/usr/bin/xattr",
        args:           ["-dr", "com.apple.quarantine", "{{appdir}}/Daedalus.app"],
        writable_paths: ["{{appdir}}/Daedalus.app"]
  end

  # ~/.daedalus holds the user's workspaces and database, so it is never
  # removed here, not even by --zap.
  zap trash: [
    "~/Library/Application Support/dev.daedalus.app",
    "~/Library/Caches/dev.daedalus.app",
    "~/Library/Preferences/dev.daedalus.app.plist",
  ]
end
