# Generated by scripts/homebrew-cask.ts in Bakar0/daedalus. Do not edit by hand.
cask "daedalus" do
  arch arm: "arm64", intel: "x64"

  version "0.11.2"
  sha256 arm:   "614e64a67db39c4b459a3f9192b95e04ab78b4f64fbb0f1ac22875fc36cdcc8f",
         intel: "1034273382dad25490e231385b11548e751cef933e68473e00590775ddd9acaf"

  url "https://github.com/Bakar0/daedalus/releases/download/v#{version}/stable-macos-#{arch}-Daedalus.dmg"
  name "Daedalus"
  desc "Desktop app and CLI for running coding agents in tmux"
  homepage "https://github.com/Bakar0/daedalus"

  livecheck do
    url :url
    strategy :github_latest
  end

  # The app updates itself from GitHub Releases, so `brew upgrade` leaves it
  # alone unless asked with --greedy.
  auto_updates true
  depends_on macos: :sonoma

  app "Daedalus.app"
  # Puts `daedal` on PATH. The launcher runs the CLI inside the app.
  binary "#{appdir}/Daedalus.app/Contents/Resources/bin/daedal"

  # This build is not notarized. Homebrew quarantines what it installs, and
  # Gatekeeper refuses to open an unnotarized app from quarantine.
  postflight_steps do
    run "/usr/bin/xattr",
        args:           ["-dr", "com.apple.quarantine", "{{appdir}}/Daedalus.app"],
        writable_paths: ["{{appdir}}/Daedalus.app"]
  end

  # ~/.daedalus holds the user's workspaces and database, so it is never
  # removed here, not even by --zap.
  zap trash: [
    "~/Library/Application Support/dev.daedalus.app",
    "~/Library/Caches/dev.daedalus.app",
    "~/Library/Preferences/dev.daedalus.app.plist",
  ]
end
