# AUTO-GENERATED by scripts/gen-formula.ts on each release — do not edit by hand.
class Servant < Formula
  desc "AI servant CLI — enhances developer and coding-agent workflows"
  homepage "https://github.com/Bakar0/ai-servant-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Bakar0/ai-servant-cli/releases/download/v0.1.0/servant-darwin-arm64.tar.gz"
      sha256 "83f37cd76abbee0a7a5c80d21ee3aa50febf319d1ba074492e11fedb4055cf67"
    end
    on_intel do
      url "https://github.com/Bakar0/ai-servant-cli/releases/download/v0.1.0/servant-darwin-x64.tar.gz"
      sha256 "fc3c41db5fbf68d3fc27c11f2295b2bf7ee25ce71de51c843380571d36c84080"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Bakar0/ai-servant-cli/releases/download/v0.1.0/servant-linux-x64.tar.gz"
      sha256 "8746df2b9d324a516072fb46fd000b79966a0d3116282bbbf2c4000420a2ebae"
    end
  end

  def install
    bin.install "servant"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/servant --version")
  end
end
