# AUTO-GENERATED by scripts/gen-formula.ts on each release — do not edit by hand.
class Servant < Formula
  desc "AI servant CLI — enhances developer and coding-agent workflows"
  homepage "https://github.com/Bakar0/ai-servant-cli"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Bakar0/ai-servant-cli/releases/download/v0.0.1/servant-darwin-arm64.tar.gz"
      sha256 "0524b41eaaba013aca4348df6bc036c55fa5f8b24e7d111489c28541714e4c08"
    end
    on_intel do
      url "https://github.com/Bakar0/ai-servant-cli/releases/download/v0.0.1/servant-darwin-x64.tar.gz"
      sha256 "2d990054773fa2f8b56983551a77bc251aa396cebe0a9617adafe1b50d7a045b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Bakar0/ai-servant-cli/releases/download/v0.0.1/servant-linux-x64.tar.gz"
      sha256 "b963deb7114b4cf716c74fcd1374751f44abab719545c3a154a315aa66afb9c4"
    end
  end

  def install
    bin.install "servant"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/servant --version")
  end
end
